"use client";
import {useEffect,useState} from "react";
import {api,ApiError} from "../lib/api";
type Block={id:string;start:string;end:string;reason:string};
export default function CalendarBlocks({operational,onChange,onBlocked}:{operational:boolean;onChange:()=>void;onBlocked:()=>Promise<void>}){
 const [items,setItems]=useState<Block[]>([]),[zone,setZone]=useState("America/Sao_Paulo"),[offset,setOffset]=useState(0),[start,setStart]=useState(""),[end,setEnd]=useState(""),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(page=offset){setBusy(true);setError("");try{const result=await api(`/admin/calendar/blocks?offset=${page}`);setItems(result.items);setZone(result.timezone);setOffset(page);}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os bloqueios.");}finally{setBusy(false);}}
 useEffect(()=>{void load(0);},[]);
 async function mutate(path:string,method:string,body?:unknown){setBusy(true);setError("");setMessage("");try{await api(path,method,body);if(method==="POST"){setStart("");setEnd("");setReason("");}onChange();await load(0);setMessage(method==="POST"?"Período bloqueado. A disponibilidade já considera este compromisso.":"Bloqueio liberado. Os demais limites do expediente continuam valendo.");}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.");if(e instanceof ApiError&&e.status===403)await onBlocked();}finally{setBusy(false);}}
 const format=(value:string)=>new Intl.DateTimeFormat("pt-BR",{timeZone:zone,dateStyle:"short",timeStyle:"short"}).format(new Date(value));
 return <section className="profile-panel"><h2>Bloquear um período específico</h2><p>Tem um compromisso pessoal? Bloqueie apenas o período necessário. Este bloqueio vale mesmo que você altere o expediente depois. Horários no fuso {zone}.</p>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}<form onSubmit={e=>{e.preventDefault();void mutate("/admin/calendar/blocks","POST",{start,end,reason});}}><fieldset disabled={busy||!operational} className="availability-fieldset"><div className="availability-absence"><label>Início <input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Fim <input type="datetime-local" required min={start||undefined} value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Motivo privado <input required maxLength={200} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary-button">Bloquear período</button></div></fieldset></form><h3>Bloqueios ativos</h3><button type="button" className="secondary-button" disabled={busy} onClick={()=>load()}>Atualizar lista</button>{!busy&&!items.length&&<p>Nenhum bloqueio nesta página.</p>}<ul className="calendar-blocks">{items.map(item=><li key={item.id}><strong>{format(item.start)} até {format(item.end)}</strong><p>{item.reason}</p><button type="button" className="secondary-button" disabled={busy||!operational} onClick={()=>mutate(`/admin/calendar/blocks/${item.id}`,"DELETE")}>Liberar período</button></li>)}</ul><div className="profile-actions"><button type="button" disabled={busy||offset===0} onClick={()=>load(Math.max(0,offset-50))}>Anterior</button><button type="button" disabled={busy||items.length<50} onClick={()=>load(offset+50)}>Próxima</button></div></section>;
}
