"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {api,ApiError} from "../lib/api";
import type {PublicPageData} from "./PublicProfessionalPage";
type Availability={timezone:string;today:string;days:{date:string;available:boolean}[];slots:{start:string;end:string}[]};
type Review={name:string;email:string;serviceName:string;start:string;end:string;timezone:string;priceCents:number;depositCents:number;slotAvailable:boolean;reservationEnabled:boolean};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value/100);
export default function CustomerBooking({page}:{page:PublicPageData}){
 const [service,setService]=useState(""),[date,setDate]=useState(""),[start,setStart]=useState(""),[month,setMonth]=useState(""),[availability,setAvailability]=useState<Availability|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sent,setSent]=useState(false),[token,setToken]=useState(""),[review,setReview]=useState<Review|null>(null),[revision,setRevision]=useState(0),[cooldown,setCooldown]=useState(0);
 const initialized=useRef(false);const requests=useRef(0);const prefix=`/public/${encodeURIComponent(page.slug)}`;
 useEffect(()=>{if(initialized.current)return;initialized.current=true;const secret=new URLSearchParams(window.location.hash.slice(1)).get("token");if(secret){setToken(secret);window.history.replaceState(null,"",window.location.pathname);}else{api(`${prefix}/review`).then(setReview).catch(()=>{});}},[prefix]);
 useEffect(()=>{if(!cooldown)return;const timer=window.setTimeout(()=>setCooldown(v=>v-1),1000);return()=>window.clearTimeout(timer);},[cooldown]);
 useEffect(()=>{if(!service)return;const id=++requests.current;setAvailability(null);setBusy(true);setError("");api(`${prefix}/availability?serviceId=${service}${date?`&date=${date}`:""}`).then((result:Availability)=>{if(id===requests.current){setAvailability(result);setMonth(value=>value||result.today.slice(0,7));}}).catch(e=>{if(id===requests.current)setError(e instanceof Error?e.message:"Não foi possível consultar os horários.");}).finally(()=>{if(id===requests.current)setBusy(false);});return()=>{requests.current++;};},[service,date,prefix,revision]);
 async function request(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy||cooldown)return;const form=new FormData(event.currentTarget);setBusy(true);setError("");try{await api(`${prefix}/access-links`,"POST",{serviceId:service,start,name:form.get("name"),email:form.get("email")});setSent(true);setCooldown(60);}catch(e){setError(e instanceof Error?e.message:"Não foi possível solicitar o link.");if(e instanceof ApiError){setCooldown(e.retryAfter);if(e.status===409){setStart("");setRevision(v=>v+1);}}}finally{setBusy(false);}}
 async function verify(){if(busy)return;setBusy(true);setError("");try{setReview(await api(`${prefix}/access-links/consume`,"POST",{token}));setToken("");}catch(e){setError(e instanceof Error?e.message:"Não foi possível verificar.");}finally{setBusy(false);}}
 const chosen=page.services.find(item=>item.id===service);
 const time=(value:string,zone=availability?.timezone||page.timezone)=>new Intl.DateTimeFormat("pt-BR",{timeZone:zone,hour:"2-digit",minute:"2-digit"}).format(new Date(value));
 const visible=availability?.days.filter(day=>day.date.startsWith(month))||[];
 const offset=month?(new Date(`${month}-01T12:00:00Z`).getUTCDay()+6)%7:0;
 function moveMonth(amount:number){const value=new Date(`${month}-01T12:00:00Z`);value.setUTCMonth(value.getUTCMonth()+amount);setMonth(value.toISOString().slice(0,7));}
 return <main className="professional-content" style={{maxWidth:940,margin:"0 auto"}}><Link href={`/a/${page.slug}`}>← Voltar para {page.name}</Link><h1>Planeje seu atendimento</h1><p>Escolha o serviço, a data e o horário. Depois, verifique seu email para revisar os dados.</p><p className="calendar-note">Esta etapa permite consultar e revisar. A criação de reservas e o pagamento ainda estão em preparação; nenhum horário será bloqueado.</p><ol className="booking-steps" aria-label="Etapas"><li>Serviço</li><li>Data</li><li>Horário</li><li>Contato</li><li>Verificação</li><li>Revisão</li></ol>{error&&<p role="alert" className="form-error">{error}</p>}
 {review?<section className="profile-panel"><h2>Revise seu atendimento</h2><p>Email verificado: {review.email}</p><p>{review.name} · {review.serviceName}</p><p>{new Intl.DateTimeFormat("pt-BR",{timeZone:review.timezone,dateStyle:"full"}).format(new Date(review.start))} · {time(review.start,review.timezone)}–{time(review.end,review.timezone)}</p><p>Valor atual: {money(review.priceCents)} · Entrada: {money(review.depositCents)}</p><p>{review.slotAvailable?"Horário disponível na consulta. Ainda não está reservado.":"Esse horário não está mais disponível. Escolha outro."}</p><p>A revisão não confirma um agendamento. A criação da reserva será habilitada na próxima etapa do sistema.</p><button type="button" className="secondary-button" onClick={()=>{setReview(null);setSent(false);setStart("");setRevision(v=>v+1);}}>Escolher outro atendimento</button></section>:token?<section className="profile-panel"><h2>Confirme seu email</h2><p>Clique para usar o link recebido e abrir a revisão. Ele vale por 15 minutos e só pode ser usado uma vez.</p><button type="button" className="primary-button" disabled={busy} onClick={verify}>Verificar email e revisar</button><p><button type="button" className="secondary-button" onClick={()=>setToken("")}>Solicitar um novo link</button></p></section>:<>
 <section className="profile-panel"><h2>1. Escolha o serviço</h2><div className="profile-actions">{page.services.map(item=><button type="button" className="secondary-button" aria-pressed={service===item.id} key={item.id} disabled={busy} onClick={()=>{setService(item.id);setDate("");setStart("");setSent(false);setMonth("");}}>{item.name} · {item.durationMinutes} min · {money(item.priceCents)}</button>)}</div></section>
 {service&&<section className="profile-panel"><h2>2. Escolha a data</h2>{busy&&<p role="status">Consultando horários…</p>}{!availability&&!busy&&<button type="button" onClick={()=>setRevision(v=>v+1)}>Tentar novamente</button>}{availability&&<><p>Fuso: {availability.timezone}. Dias sem horários ficam desabilitados.</p><div className="profile-actions"><button type="button" disabled={month<=availability.today.slice(0,7)} onClick={()=>moveMonth(-1)} aria-label="Mês anterior">‹</button><strong>{new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${month}-01T12:00:00Z`))}</strong><button type="button" disabled={month>=availability.days[availability.days.length-1].date.slice(0,7)} onClick={()=>moveMonth(1)} aria-label="Próximo mês">›</button></div><div className="booking-dates">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(day=><span key={day}>{day}</span>)}{Array.from({length:offset},(_,i)=><span key={`empty-${i}`}/>)}{Array.from({length:Number(visible[0]?.date.slice(8)||1)-1},(_,i)=><span key={`past-${i}`}/>)}{visible.map(day=><button type="button" key={day.date} disabled={!day.available||busy} aria-pressed={date===day.date} aria-label={`${day.date.split("-").reverse().join("/")}${day.available?", disponível":", sem horários"}`} onClick={()=>{setDate(day.date);setStart("");setSent(false);}}>{Number(day.date.slice(8))}</button>)}</div>{!availability.days.some(day=>day.available)&&<p>Nenhum horário disponível para este serviço nos próximos 60 dias.</p>}</>}</section>}
 {date&&availability&&<section className="profile-panel"><h2>3. Escolha o horário</h2><div className="profile-actions">{availability.slots.map(slot=><button type="button" key={slot.start} className="secondary-button" aria-pressed={start===slot.start} onClick={()=>{setStart(slot.start);setSent(false);}}>{time(slot.start)}</button>)}</div>{!availability.slots.length&&<p>Nenhum horário livre nesta data. Escolha outra.</p>}</section>}
 {start&&chosen&&<section className="profile-panel"><h2>4. Seus dados</h2><p>{chosen.name} · {date.split("-").reverse().join("/")} às {time(start)}. O link preserva essa escolha para revisão; não bloqueia o horário.</p><form onSubmit={request}><fieldset disabled={busy}><label>Nome<input name="name" required maxLength={100} autoComplete="name"/></label><label>Email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><button className="primary-button" disabled={cooldown>0}>{cooldown?`Aguarde ${cooldown}s`:sent?"Reenviar link":"Receber link de verificação"}</button></fieldset></form>{sent&&<p role="status">Se a solicitação puder ser atendida, você receberá um link. Confira seu email e a pasta de spam. O link expira em 15 minutos; ao solicitar outro, o anterior deixa de funcionar.</p>}</section>}
 </>}
 </main>;
}
