"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {api,ApiError} from "../lib/api";
import CalendarBlocks from "./CalendarBlocks";
type Day={date:string;start:string;end:string;exception:boolean;reason:string;status:"FREE"|"OCCUPIED"|"UNAVAILABLE";occupiedCount:number;periods:{start:string;end:string}[]};
type Event={id:string;kind:"BLOCK"|"HOLD";start:string;end:string;protectedStart:string;protectedEnd:string;expiresAt:string|null;reason:string};
type Calendar={timezone:string;today:string;from:string;days:Day[];events:Event[];generatedAt:string;intervalMinutes:number};
type Mode="month"|"week"|"day";
const labels={FREE:"Horários livres, sem atendimentos ocupando a agenda",OCCUPIED:"Com ocupações e horários disponíveis",UNAVAILABLE:"Sem horários disponíveis"};
const weekdays=["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"];
function shift(date:string,days:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function monday(date:string){return shift(date,-((new Date(`${date}T12:00:00Z`).getUTCDay()+6)%7));}
function move(date:string,direction:number,mode:Mode){if(mode!=="month")return shift(date,direction*(mode==="week"?7:1));const d=new Date(`${date.slice(0,7)}-01T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+direction);return d.toISOString().slice(0,10);}
export default function ProfessionalCalendar({operational,onBlocked}:{operational:boolean;onBlocked:()=>Promise<void>}){
 const [data,setData]=useState<Calendar|null>(null),[date,setDate]=useState(""),[mode,setMode]=useState<Mode>("month"),[revision,setRevision]=useState(0),[blocksRevision,setBlocksRevision]=useState(0),[busy,setBusy]=useState(false),[mutating,setMutating]=useState(false),[error,setError]=useState("");const request=useRef(0);
 useEffect(()=>{const timer=window.setInterval(()=>setRevision(v=>v+1),60000);return()=>window.clearInterval(timer);},[]);
 useEffect(()=>{
  const id=++request.current,count=mode==="month"?42:mode==="week"?7:1;
  const from=date?(mode==="month"?monday(`${date.slice(0,7)}-01`):mode==="week"?monday(date):date):"";
  setBusy(true);setError("");setData(current=>current?.from===from&&current.days.length===count?current:null);
  (async()=>{try{const result:Calendar=await api(`/admin/calendar?days=${count}${from?`&from=${from}`:""}`);if(id!==request.current)return;if(!date){setDate(result.today);return;}setData(result);}catch(e){if(id===request.current)setError(e instanceof Error?e.message:"Não foi possível carregar o calendário.");}finally{if(id===request.current)setBusy(false);}})();return()=>{request.current++;};
 },[date,mode,revision]);
 async function release(event:Event){setMutating(true);setError("");try{await api(`/admin/calendar/blocks/${event.id}`,"DELETE");setRevision(v=>v+1);setBlocksRevision(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"Não foi possível liberar.");if(e instanceof ApiError&&e.status===403)await onBlocked();}finally{setMutating(false);}}
 const format=(instant:string)=>new Intl.DateTimeFormat("pt-BR",{timeZone:data?.timezone||"America/Sao_Paulo",dateStyle:"short",timeStyle:"short"}).format(new Date(instant));
 const dateLabel=(value:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC",...options}).format(new Date(`${value}T12:00:00Z`));
 const eventsFor=(day:Day)=>data?.events.filter(e=>Date.parse(e.protectedStart)<Date.parse(day.end)&&Date.parse(e.protectedEnd)>Date.parse(day.start)&&(!e.expiresAt||Date.parse(e.expiresAt)>Date.now()))||[];
 return <><p className="eyebrow">SUA ROTINA, À VISTA</p><h1>Calendário</h1><p><Link href="/painel/horarios">Configurar expediente, intervalos e folgas</Link></p>
  <div className="calendar-toolbar"><div className="availability-mode" role="group" aria-label="Visualização do calendário">{(["month","week","day"] as Mode[]).map(value=><button key={value} type="button" className="secondary-button" aria-pressed={mode===value} onClick={()=>setMode(value)}>{{month:"Mês",week:"Semana",day:"Dia"}[value]}</button>)}</div><div className="availability-absence"><button type="button" disabled={!date||busy} onClick={()=>setDate(move(date,-1,mode))} aria-label="Período anterior">‹</button><button type="button" onClick={()=>{setDate("");setRevision(v=>v+1);}}>Hoje</button><button type="button" disabled={!date||busy} onClick={()=>setDate(move(date,1,mode))} aria-label="Próximo período">›</button><label>Ir para data <input type="date" min="2000-02-01" max="2100-11-30" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label><button type="button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Atualizar</button></div></div>
  <h2 className="calendar-period-title">{date&&dateLabel(date,mode==="day"?{day:"numeric",month:"long",year:"numeric"}:{month:"long",year:"numeric"})}</h2>
  <ul className="calendar-legend"><li><span className="calendar-dot occupied"/>Com ocupações</li><li><span className="calendar-dot unavailable"/>Sem horários disponíveis</li><li><span className="calendar-dot free"/>Livre, sem atendimentos</li></ul>
  {error&&<p role="alert" className="form-error">{error}</p>}{busy&&<p role="status">Atualizando calendário…</p>}
  {data&&<><p className="calendar-note">Fuso: {data.timezone}. Clique em um dia para ver a lista. Vermelho tem prioridade quando não há horário para nenhum serviço ativo, considerando expediente, bloqueios, duração, antecedência de 24h e horizonte de 60 dias.</p>
   {mode!=="day"?<div className={`agenda-grid ${mode}`} aria-label={mode==="month"?"Calendário mensal":"Calendário semanal"}>{weekdays.map(day=><div className="agenda-weekday" key={day}>{day}</div>)}{data.days.map(day=>{const events=eventsFor(day);return <button type="button" key={day.date} className={`agenda-cell ${day.date===data.today?"today":""} ${mode==="month"&&day.date.slice(0,7)!==date.slice(0,7)?"outside":""}`} aria-label={`${dateLabel(day.date,{day:"numeric",month:"long"})}: ${labels[day.status]}`} onClick={()=>{setDate(day.date);setMode("day");}}><span className="agenda-cell-heading"><span>{Number(day.date.slice(8))}</span><span className={`calendar-dot ${day.status.toLowerCase()}`} aria-hidden="true"/></span>{mode==="week"&&<span className="agenda-cell-hours">{day.periods.length?day.periods.map(p=>`${p.start.slice(0,5)}–${p.end.slice(0,5)}`).join(" · "):"Folga"}</span>}{events.slice(0,mode==="month"?2:4).map(event=><span className={`agenda-chip ${event.kind.toLowerCase()}`} key={event.id}>{event.kind==="BLOCK"?"Bloqueio":"Ocupação temporária"}</span>)}{events.length>(mode==="month"?2:4)&&<small>+{events.length-(mode==="month"?2:4)}</small>}{day.date===data.today&&<small className="agenda-today-label">Hoje</small>}</button>;})}</div>:data.days.map(day=><section className="profile-panel" key={day.date}><h2 className="calendar-period-title">Atendimentos e bloqueios do dia</h2><p><Link className="secondary-button" href={`/painel/horarios?date=${day.date}#data-especifica`}>Configurar horários somente deste dia</Link></p><div className="calendar-hours"><strong>{day.periods.length?"Expediente":"Sem atendimento"}</strong>{day.periods.map((p,i)=><span key={i}> · {p.start.slice(0,5)}–{p.end.slice(0,5)}</span>)}{day.exception&&<p>{day.reason||"Data especial"}</p>}</div>{!eventsFor(day).length&&<p className="calendar-empty">Nenhum atendimento ou bloqueio registrado neste dia.</p>}<ol className="agenda-day-list">{eventsFor(day).map(event=><li key={event.id} className={`calendar-event ${event.kind.toLowerCase()}`}><strong>{event.kind==="BLOCK"?"Bloqueado":"Ocupação temporária"}</strong><p>{format(event.start)} até {format(event.end)}</p>{event.reason&&<p>{event.reason}</p>}{event.protectedStart!==event.start||event.protectedEnd!==event.end?<small>Inclui preparação: {format(event.protectedStart)} até {format(event.protectedEnd)}</small>:null}{event.expiresAt&&<p>Expira em {format(event.expiresAt)}. Não é reserva confirmada.</p>}{event.kind==="BLOCK"&&<button type="button" className="secondary-button" disabled={!operational||mutating} onClick={()=>release(event)}>Liberar período</button>}</li>)}</ol></section>)}
   <p className="calendar-note">O expediente exibido é a configuração atual. Reservas de clientes ainda não estão habilitadas; amarelo indica ocupações temporárias reais. Bloqueios pessoais não contam como atendimentos.</p>
  </>}
  <details className="calendar-block-editor"><summary>Adicionar ou gerenciar bloqueios</summary><CalendarBlocks key={blocksRevision} operational={operational} onBlocked={onBlocked} onChange={()=>setRevision(v=>v+1)}/></details>
 </>;
}
