"use client";
import {useEffect,useState} from "react";
import {api} from "../lib/api";
import Link from "next/link";
import PublicProfessionalPage,{type PublicPageData} from "./PublicProfessionalPage";
type Status={published:boolean;canPublish:boolean;missingRequirements:string[];path:string};
export default function Publication(){
 const [status,setStatus]=useState<Status|null>(null),[page,setPage]=useState<PublicPageData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError("");try{const [state,profile]=await Promise.all([api("/admin/publication"),api("/admin/profile")]);const services=[];let offset=0;for(;;){const result=await api(`/admin/services?offset=${offset}`);services.push(...result.items.filter((s:{active:boolean})=>s.active));offset+=result.items.length;if(offset>=result.total||!result.items.length)break;}setStatus(state);setPage({...profile,hasLogo:!!profile.logoVersion,bookingAvailable:false,services});}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar.");}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 async function publish(){setBusy(true);setError("");try{await api("/admin/publication","POST");await load();}catch(e){const message=e instanceof Error?e.message:"Não foi possível publicar.";await load();setError(message);}finally{setBusy(false);}}
 async function unpublish(){setBusy(true);setError("");try{await api("/admin/publication","DELETE");await load();}catch(e){setError(e instanceof Error?e.message:"Não foi possível retirar a página.");}finally{setBusy(false);}}
 return <><h1>Publicação da página</h1><p>Confira como seu negócio será apresentado aos clientes.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="secondary-button" disabled={busy} onClick={load}>{busy?"Carregando…":"Atualizar prévia"}</button>{status&&<section className="profile-panel"><h2>{status.published?"Página publicada":"Sua página está em preparação"}</h2><p>Endereço da página: <code>{status.path}</code></p>{status.missingRequirements.length>0?<><p>{status.published?"Requisitos que precisam de atenção:":"Para liberar a publicação:"}</p><ul>{status.missingRequirements.map(item=><li key={item}>{item}</li>)}</ul></>:<p>Todos os requisitos de publicação estão atendidos.</p>}<p>{status.published?"Seus serviços e contatos estão visíveis na página pública. Alterações salvas no perfil e nos serviços aparecem nela.":"Ao publicar, nome, descrição, logomarca, contatos, local e serviços ativos ficarão visíveis para qualquer pessoa com o link."} A chave PIX e as observações privadas não são exibidas. O agendamento online ainda está em preparação.</p>{!status.published&&<button className="primary-button" disabled={busy||!status.canPublish} onClick={publish}>{busy?"Aguarde…":status.canPublish?"Publicar página":"Publicação aguardando requisitos"}</button>}{status.published&&<p><a className="primary-button" href={status.path} target="_blank" rel="noopener noreferrer">Ver página pública</a> <Link className="secondary-button" href="/painel/compartilhar">Compartilhar página</Link></p>}{status.published&&<button className="secondary-button" disabled={busy} onClick={unpublish}>Retirar página do ar</button>}</section>}{page&&<PublicProfessionalPage page={page} preview/>}</>;
}
