"use client";
import {useEffect,useState} from "react";
import {api} from "../lib/api";
type Slot={start:string;end:string};
type Preview={timezone:string;intervalMinutes:number;candidates:Slot[];sequence:Slot[]};
export default function SlotPreview({timezone,unsaved}:{timezone:string;unsaved:boolean}){
 const [services,setServices]=useState<{id:string;name:string}[]>([]),[service,setService]=useState(""),[date,setDate]=useState(""),[result,setResult]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{try{const items=[];let offset=0;for(;;){const page=await api(`/admin/services?offset=${offset}`);items.push(...page.items.filter((s:{active:boolean})=>s.active));offset+=page.items.length;if(offset>=page.total||!page.items.length)break;}if(active){setServices(items);setService(items[0]?.id||"");}}catch(e){if(active)setError(e instanceof Error?e.message:"Falha ao carregar serviços.");}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 useEffect(()=>{setResult(null);},[unsaved]);
 async function calculate(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setResult(null);try{setResult(await api(`/admin/availability/slots?serviceId=${encodeURIComponent(service)}&date=${encodeURIComponent(date)}`));}catch(e){setError(e instanceof Error?e.message:"Não foi possível calcular.");}finally{setBusy(false);}}
 const time=(value:string)=>new Intl.DateTimeFormat("pt-BR",{timeZone:result?.timezone||timezone,hour:"2-digit",minute:"2-digit"}).format(new Date(value));
 return <section className="profile-panel"><h2>Confira como fica o seu dia</h2><p>Escolha um serviço e uma data para calcular os horários com a configuração salva. Fuso: {timezone}. Antecedência de 24 horas, horizonte de 60 dias e inícios a cada 15 minutos.</p>{unsaved&&<p role="status">Salve suas alterações acima antes de calcular a prévia.</p>}{error&&<p role="alert" className="form-error">{error}</p>}{loading?<p>Carregando serviços…</p>:!services.length?<p>Cadastre e ative um serviço na aba Serviços para conferir os horários.</p>:<form onSubmit={calculate}><fieldset disabled={busy||unsaved} className="availability-fieldset"><div className="availability-absence"><label>Serviço <select required value={service} onChange={e=>{setService(e.target.value);setResult(null);}}>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Data no fuso do estabelecimento <input type="date" required value={date} onChange={e=>{setDate(e.target.value);setResult(null);}}/></label><button className="primary-button">{busy?"Calculando…":"Calcular horários"}</button></div></fieldset></form>}{result&&!unsaved&&<div aria-live="polite"><h3>Uma sugestão de sequência</h3><p>Intervalo mínimo: {result.intervalMinutes} min. Duração e tempos de preparação do serviço também são considerados.</p>{!result.sequence.length?<p>Nenhum horário cabe nesta data. Confira folgas, expediente, duração, antecedência e fuso. Períodos que atravessam mudança de horário de verão não são oferecidos nesta etapa.</p>:<ul className="slot-preview-list">{result.sequence.map(slot=><li key={slot.start}>{time(slot.start)} – {time(slot.end)}</li>)}</ul>}<details><summary>Ver todos os inícios possíveis ({result.candidates.length})</summary><p>São alternativas de escolha. Horários próximos podem se sobrepor e não devem ser usados juntos.</p><ul className="slot-preview-list">{result.candidates.map(slot=><li key={slot.start}>{time(slot.start)} – {time(slot.end)}</li>)}</ul></details><p>Esta é uma prévia de expediente, não uma reserva. A agenda ainda não está aberta para agendamentos.</p></div>}</section>;
}
